name: Grammar and spelling check
on: push
jobs:
  grammar-spelling:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{ github.token }}
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: "11"
      - name: Install texttidote
        run: |
          wget https://github.com/sylvainhalle/textidote/releases/download/v0.8.2/textidote_0.8.2_all.deb
          sudo dpkg -i textidote_0.8.2_all.deb
          rm textidote_0.8.1_all.deb
      - name: Grammar/Spell check files
        run: |
          jq  -r '.words[]' .vscode/cspell.json   > .github/mydict.txt
          textidote --dict .github/mydict.txt --check de **/*.md
  cspells-spellchecking:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Check out the code
      - uses: actions/setup-node@v1
        name: Run spell check
        with:
          node-version: "12"
      - run: npm install -g cspell
      - run: |
          cspell --config ./vscode/cspell.json README.md
